version: '2'
services:
  petplanet-app:
    image: mikexfreeze/petplanet:0.0.1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://duandiwang.com:5432/pet_planet
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  # petplanet-postgresql:
  #   extends:
  #     file: postgresql.yml
  #     service: petplanet-postgresql
